---

- hosts: all
  become: true
  tasks:

  - name: install apache2 puckage
    apt:
      name:
        - apache2
        - vim-nox    
      state: latest
      update_cache: yes 
    when: ansible_distribution_version == "Ubuntu"
 


