---

- hosts: internal_server  
  become: true
  tasks:

  - name: install apache2 and vim-nox
    tags: apache 
    apt:
      name:
        - apache2
        - vim-nox    
      state: latest
      update_cache: yes

- hosts: external 
  become: true
  tasks: 
  
  - name: usage of the module FETCH
    tags: fetch
    unarchive:
      url: https://wingware.com/pub/wing-101/9.1.1.1/wing-101-9_9.1.1-1_amd64.deb 
      dest: /root/ansible_execise/wing
      mode: 644
      owner: root
      group: root 
                  
 
    when: ansible_distribution_version == "Ubuntu"

  - name: copy ttml default page on managed server>
    tags: html_page
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 644

  - name: install vim-air on internal
    tags: vim_air
    apt:
      name: vim-airline
       
 
- hosts: client
  become: true
  pre_tasks:
  
  - name: install vim-airline
    apt: 
      name:  vim-airline
        
      
            
         
 

