---

- hosts: all
  become: true
  tasks:

  - name: install apache2 puckage
    apt:
      name: apache2
      state: latest
 
  - name: remove vim-nox
    apt:
      name: vim-nox
      state: absent   
  
